<!-- VERSION #1.0 , lAST EDITED BY MAYAR -->
<?php
require_once ("assets/layouts/header.php");
require_once ("assets/session.php");
require_once ("assets/db_connection.php");
require_once ("assets/classes/book.php");
require_once ("assets/classes/sheet.php");
require_once ("assets/classes/electronicComponent.php");

$book=new book($connection);
$sheet=new sheet ($connection);
$electric = new electronicComponent($connection);
?>

<div id="header-img">

        <h1>Welcome to Exchange</h1>

</div>

<?php

$result1=$book->countBooks();
$data1=mysqli_fetch_assoc($result1);

$result2=$sheet->countSheets();
$data2=mysqli_fetch_assoc($result2);

$result3=$electric->countElectric();
$data3=mysqli_fetch_assoc($result3);


?>

<div class="content">
        <div class="container">
                <!---top-row numbers GENERATED BY DB--->
            <h1>Our Top Categories</h1>
            <div class="top-row">
                    <div class="col-xs-4">
                            <div class="top-row-col1 text-center">
                                    <h2>Books</h2>
                                    <img class="r-img text-center img-circle" src="img/book.jpg" title="name" />
                                    <h4>TOTAL</h4>
                                    <label>
                                        <?php
                                            echo $data1['total'] ;

                                        ?>
                                    </label>
                                    <a class="r-list-w" href="products.php?category=books"><img src="img/list-icon.png" title="list" /></a>
                            </div>
                    </div>
                    <div class="col-xs-4">
                            <div class="top-row-col1 text-center">
                                    <h2>Sheets</h2>
                                    <img class="r-img img-circle text-center" src="img/sheet.jpg" title="name" />
                                    <h4>TOTAL</h4>
                                    <label><?php
                                        echo $data2['total']  ;

                                        ?></label>
                                    <a class="r-list-w" href="products.php?category=sheets"><img src="img/list-icon.png" title="list" /></a>
                            </div>
                    </div>
                    <div class="col-xs-4">
                            <div class="top-row-col1 text-center">
                                    <h2 style="font-size:1.9em;">Electronic Components</h2>
                                    <img class="r-img img-circle text-center" src="img/electric.jpg" title="name" />
                                    <h4>TOTAL</h4>
                                    <label><?php
                                        echo $data3['total'] ;

                                        ?></label>
                                    <a class="r-list-w" href="products.php?category=<?php echo urlencode('electronic components'); ?>"><img src="img/list-icon.png" title="list" /></a>
                            </div>
                    </div>
                    <div class="clearfix"> </div>
            </div>

            <div class="about">
                <h1>ABOUT US</h1>
                <div class="row">

                    <div class="col-md-8 abt">
                        <span><i class="fa fa-share-alt"></i></span>
                        <p style="text-align: justify;">
                            This web site is designed to encourage the concept of sharing amongst students through sharing their
                            college stuff and other stuff either by giving it away for free or lend it for some time
                            or selling it by an appropriate
                            price. Students can add items to share them with others, wish items added by others and delete their own items
                            if they aren't available any more.
                        </p>
                    </div>
                    <div class="col-md-8 abt">
                        <span><i class="fa fa-share-alt"></i></span>
                        <p style="text-align: justify;">
                            Feel free to register and share what you have with others and get in touch with others who share
                            their items as well.
                            You can add Books, Sheets, Hardware Components, Electric Components, Tools, Sport Equipment, Musical
                            Instrument, Tickets, Accessories and Others.
                        </p>
                    </div>

                </div>

            </div>

        </div>


</div>
<?php
require_once("assets/layouts/footer.php");
?>
