<!-- VERSION #1.0 , lAST EDITED BY MAYAR -->
<?php
require_once("assets/layouts/header.php")
?>
<?php
    function __autoload ($class_name)
    {
        require_once("assets/classes/".$class_name.".php");
    }
?>
<?php require_once("assets/db_connection.php")?>
<?php require_once("assets/functions.php")?>
<?php
    $cat;
    $obj;
    $result;
if (isset($_GET["category"])) {

    $cat=$_GET["category"];
    $obj = getCategory($cat, $connection);
    if (!isset($obj))
        redirect_to("index.php");

    if (isset($_GET["sort"]))
        {
            $sort=$_GET["sort"];
            if ($sort=="most recent") {

                $result = $obj->getMostRecent();
            }
            //else by price
            else if($sort=="Price"){
                $result=$obj->sortByPrice();
            }

            //else book categories and sheet departmnets
        }
    else if (isset($_GET["filter"])){

        $filter = $_GET['filter'];
         if ($filter=="department" && isset($_GET["name"]))
        {
            $result=$obj->getSheetsByDep($_GET["name"]);
            // $result =get by department ($_GET['name'])
        }
        else if ($filter=="year" && isset($_GET["num"]))
        {
            $result=$obj->getSheetsByYear($_GET["num"]);
            // $result =get by year ($_GET['num'])
        }
        else if ($filter=="semester" && isset($_GET["num"]))
        {
            $result=$obj->getSheetsBySemester($_GET["num"]);
        }
        else if($filter=="bookcat" && isset($_GET["name"]))
        {
            $result=$obj->getBooksByCategory($_GET["name"]);
            // $result =get by bookcategory ($_GET['name'])
        }

    }
    else if(isset($_GET["name"]))
    {
        $result = $obj->searchByName($_GET["name"]);
        if(mysqli_num_rows($result) == 0)
            echo "No results were found";
    }
    //condition mai hena

   else{
       $result = $obj->getAllItems();
   }

}
else
{
    redirect_to("index.php");
}
?>


<section>
    <div class="container">
        <div class="row margin-top">

                <?php echo displaySideBar($cat ,$obj); ?>


            <!-- Get ALL Products for a certain section (from url) -->
            <div class="col-sm-9 padding-right">
                <div class="features_items"><!--features_items-->

                    <h2 class="title text-center"><?php echo ucwords($cat); ?></h2>
                    <p class="sorting"> Sort By:
                        <a href="products.php?category=<?php echo urlencode($cat); ?>&sort=<?php echo urlencode("most recent"); ?>">Most Recent</a>
                        | <a href="products.php?category=<?php echo urlencode($cat); ?>&sort=<?php echo urlencode("Price"); ?>">Price</a>
                    </p>
                    <br />

                    <?php while ($item=mysqli_fetch_assoc($result)){ ?>
                    <div class="col-sm-4"> <!-- generated by database -->
                        <a class="product-link" href="product-details.php?category=<?php echo urlencode($cat)."&id={$item['Id']}";?>"> <!-- SHOULD REDIRECT TO A PRODUCT ID AND CATEGORY NAME -->
                            <div class="product-image-wrapper">
                                <div class="single-products">
                                    <div class="productinfo text-center">
                                        <img src="<?php echo $item['image'] ;?>" />
                                       <span class="small"><?php echo $item['Date_time'] ;?> </span>
                                        <p style="font-size:1.1em;"><?php echo $item['Name'];?></p>
                                        <h2>Price : <?php echo $item['Price'];?></h2>

                                        <a href="addWish.php?category=<?php echo $cat; ?>&item=<?php echo $item['Id']; ?>" class="btn btn-default add-to-cart"><i class="fa fa-star"></i>Add to wishlist</a>
                                    </div>
                                </div>
                            </div>
                        </a>

                    </div>
                    <?php } ?>



                </div><!--features_items-->
            </div>
        </div>


    </div>
    </div>
</section>



<?php
require_once("assets/layouts/footer.php")
?>
